# Generated by Django 3.0.2 on 2020-01-04 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254)),
                ('amount_limit', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id_history', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.FloatField()),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 4, 5, 33, 48, 30823))),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogli.Product')),
            ],
        ),
    ]
