# Generated by Django 3.0.1 on 2020-01-05 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogli', '0002_auto_20200105_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='id_product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 18, 55, 22, 246694)),
        ),
    ]
