# Generated by Django 3.0.1 on 2020-01-05 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogli', '0003_auto_20200105_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='credit_card_used',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 5, 19, 33, 9, 740097)),
        ),
    ]
