# Generated by Django 3.0.2 on 2020-01-06 04:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mogli', '0004_auto_20200105_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 4, 56, 52, 234005)),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogli.User')),
            ],
        ),
    ]
