# Generated by Django 3.0.2 on 2020-01-06 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogli', '0005_auto_20200106_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercard',
            old_name='card_number',
            new_name='credit_card_number',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 4, 59, 7, 263184)),
        ),
    ]
