# Generated by Django 3.0.1 on 2020-01-06 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogli', '0006_auto_20200106_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 54, 0, 499446)),
        ),
    ]
