# Generated by Django 3.0.2 on 2020-01-06 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mogli', '0006_auto_20200106_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 6, 32, 32, 55291, tzinfo=utc)),
        ),
    ]
