# Generated by Django 3.0.1 on 2020-01-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogli', '0007_auto_20200106_1754'),
        ('mogli', '0007_auto_20200106_0632'),
    ]

    operations = [
    ]
